/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import * as React from 'react';
import Head from "next/head";

import { api } from "~/utils/api";
import styles from "../index.module.css";
import { Button, ButtonGroup, Card, CardContent, CardMedia, Grid, Typography } from '@mui/material';
import Link from 'next/link';


const All = () => {
    const { data } = api.pokemon.getAllPokemon.useQuery()
    console.log(data);
    return (
        <>
            <Head>
                <title>Pokedex - All</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/pokedex-icon.jpg" />
            </Head>
            <main className={styles.main}>
                <h1 className={styles.title}>All Pokemons</h1>
                <ButtonGroup
                    sx={{
                        marginTop: 4
                    }}
                    variant="text" aria-label="text button group">
                    <Link href={'/add'}>
                        <Button >Add Pokemons</Button>
                    </Link>
                    <Link href={'/'}>
                        <Button >Home</Button>
                    </Link>
                </ButtonGroup>
                <div className={styles.container}>

                    <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 3 }}>
                        {data?.map((e, i) =>
                            <Grid key={i} item>
                                <Card sx={{ width: 345 }}>
                                    <CardMedia
                                        component="img"
                                        sx={{ width: 300, height: 300 }}
                                        image={e.sprite}
                                        title={e.name}
                                    />
                                    <CardContent>
                                        <Typography gutterBottom variant="h5" component="div">
                                            {e.name}
                                        </Typography>
                                        {e.types.map((type, i) =>
                                            <Typography
                                                key={i} variant="body2" color="text.secondary">
                                                {type}
                                            </Typography>
                                        )}
                                    </CardContent>
                                </Card>
                            </Grid>
                        )}


                    </Grid>

                </div>


            </main>
        </>
    );
};

export default All;